<a href="https://colab.research.google.com/github/devi12345-M/Data-analytics-using-python-/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def attendance(attended,total):
     return (attended / total) * 100

attended = int(input("classes attended:"))
total = int(input("total classes:"))

percentage = attendance(attended,total)

print("attendance percentage =",round(percentage,2),"%")

classes attended:55
total classes:66
attendance percentage = 83.33 %


In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [ ]:
import numpy as np
arr = np.array([
              [[1,2],[3,4]],
               [[5,6],[7,8]]
             ])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
